#!/usr/bin/env bash

# Produce a semver-based version string for the footer / support requests (#166).
# `git describe --tags` yields the nearest semver tag (e.g. v1.1.3) on a release commit, or
# `v1.1.3-469-g3fffeaa1` between releases. `--always` falls back to a short SHA if there are no
# tags. Requires tags in the checkout — CI must use fetch-depth: 0 (or fetch-tags) so they exist.
# (Previously CI emitted "main#<sha>", a git ref rather than a version.)
VERSION_INFO=`git describe --tags --always 2>/dev/null`
if [[ -z "${VERSION_INFO}" ]]; then
    VERSION_INFO="dev"
fi

echo "writing version file (version: ${VERSION_INFO})"
cat <<EOT > src/environments/versions.ts
// this file is automatically generated by git.version.sh script
export const versionInfo = {
    version: '${VERSION_INFO}',
};
EOT
